import type { Locale } from './themes';

/** Copy for the in-match table (turn bar, ball supply, tray, dock). */
export const MATCH_COPY = {
  'zh-CN': {
    yourTurn: '轮到你了',
    waitingFor: (name: string) => `等待 ${name} 行动`,
    roundTurn: (round: number, turn: number) => `第 ${round} 轮 · 第 ${turn} 回合`,
    finished: (winners: string) => `对局结束 · 胜者 ${winners}`,
    supply: '球供应',
    tray: '本回合拿取',
    trayHint: '点球堆拿球；同一堆点两下拿 2 个',
    trayReturn: '点击放回',
    keysHint: '1–5 选球 · Enter 确认 · Esc 清空',
    confirmTake: '确认拿取',
    clear: '清空',
    mustReturn: (count: number) => `拿完会超过 10 个，还需放回 ${count} 个：`,
    reserveOverflow: (count: number) => `你有 10 个球了，保留时会拿到大师球，先选 ${count} 个放回：`,
    returnPicked: '已选放回',
    returnReady: '放回的球选好了，确认后一起结算：',
    pickProblems: {
      notElement: '大师球不能直接拿，保留卡牌时获得。',
      empty: (ball: string) => `${ball}已经被拿完了。`,
      full: '已经选满了；点托盘里的球可以放回。',
      pairOnly: '拿同色 2 个时，不能再拿其他球。',
      pairNeedsFour: (ball: string, left: number) => `同色拿 2 个需要这堆至少 4 个（${ball}现在 ${left} 个）。`,
      invalid: '这样组合不合法：三种不同各 1 个，或同色 2 个。',
    },
    myBalls: '我的球',
    myBonuses: '加成',
    myHand: '保留手牌',
    emptyHand: '还没有保留卡牌',
    spectator: '你在观战；加入房间后才能操作。',
    score: (score: number, target: number) => `${score}/${target} 分`,
    motionOn: '动画：开',
    motionOff: '动画：关',
    reserveTop: '保留牌堆顶',
    evolution: '进化',
    evolveNeedsCatch: '这个进化要先捕获一张卡牌、加成够了才会发生；只拿球或保留不会进化。',
    seats: '控制席位',
    log: '战斗日志',
    leadersGone: '训练师都已被邀请走了。',
    handCount: (count: number) => `保留 ${count}`,
    cardsCount: (count: number) => `宝可梦 ${count}`,
  },
  'en-US': {
    yourTurn: 'Your turn',
    waitingFor: (name: string) => `Waiting for ${name}`,
    roundTurn: (round: number, turn: number) => `Round ${round} · Turn ${turn}`,
    finished: (winners: string) => `Game over · Winner ${winners}`,
    supply: 'Supply',
    tray: 'This turn',
    trayHint: 'Click a stack to pick; twice for two of a kind',
    trayReturn: 'Click to return',
    keysHint: '1–5 pick · Enter confirm · Esc clear',
    confirmTake: 'Confirm',
    clear: 'Clear',
    mustReturn: (count: number) => `This goes over 10 balls. Return ${count}:`,
    reserveOverflow: (count: number) => `You hold 10 balls; reserving gives a Master Ball. Return ${count} first:`,
    returnPicked: 'Returning',
    returnReady: 'Returns chosen; they settle when you confirm:',
    pickProblems: {
      notElement: 'Master Balls cannot be taken; reserve a card to get one.',
      empty: (ball: string) => `No ${ball} left.`,
      full: 'Selection is full; click a ball in the tray to return it.',
      pairOnly: 'Two of a kind cannot be combined with other balls.',
      pairNeedsFour: (ball: string, left: number) => `Two of a kind needs 4 in the stack (${ball}: ${left}).`,
      invalid: 'Not a legal take: three different, or two of a kind.',
    },
    myBalls: 'My balls',
    myBonuses: 'Bonuses',
    myHand: 'Reserved',
    emptyHand: 'No reserved cards yet',
    spectator: 'You are spectating; join the room to play.',
    score: (score: number, target: number) => `${score}/${target} pts`,
    motionOn: 'Motion: on',
    motionOff: 'Motion: off',
    reserveTop: 'Reserve top',
    evolution: 'Evolve',
    evolveNeedsCatch: 'This evolution needs the bonus from a catch this turn; taking balls or reserving will not trigger it.',
    seats: 'Seat',
    log: 'Battle log',
    leadersGone: 'Every trainer has been invited.',
    handCount: (count: number) => `Reserved ${count}`,
    cardsCount: (count: number) => `Pokémon ${count}`,
  },
} satisfies Record<Locale, unknown>;

export type MatchCopy = (typeof MATCH_COPY)[Locale];
